name: eventory
description: An event sourcing-inspired library targeting offline-first use, with automatic synchronization with remote
  instances when connection is available.

version: 0.0.0
homepage: https://github.com/renatoathaydes/eventory
author: renato <renato@athaydes.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta:
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
